### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by prem-prakash** [jenseng/immigrant#26]
Immigrant supports Rails 5?

```
bundle exec rake immigrant:check_keys
DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from require at /home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.9.5/lib/bundler/runtime.rb:76)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <module:Caching> at /home/rof/cache/bundler/ruby/2.3.0/bundler/gems/rails-observers-3fe157d6cbb5/lib/rails/observers/action_controller/caching.rb:10)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from require at /home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.9.5/lib/bundler/runtime.rb:76)
I, [2016-10-20T11:59:58.803236 #6232]  INFO -- sentry: ** [Raven] Raven 2.1.0 configured not to capture errors.
rake aborted!
ArgumentError: unknown keyword: only
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/rescuable.rb:50:in `rescue_from'
/home/rof/cache/bundler/ruby/2.3.0/gems/will_paginate-3.1.0/lib/will_paginate/railtie.rb:67:in `rescue_from'
/home/rof/src/github.com/mindlab-missu/penny/app/controllers/test_session/responder_controller.rb:9:in `<class:ResponderController>'
/home/rof/src/github.com/mindlab-missu/penny/app/controllers/test_session/responder_controller.rb:1:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:380:in `block in require_or_load'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:336:in `depend_on'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:252:in `require_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `each'
/home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `block in eager_load!'
/home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `each'
/home/rof/cache/bundler/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `eager_load!'
/home/rof/cache/bundler/ruby/2.3.0/gems/immigrant-0.3.5/lib/immigrant/task.rb:4:in `block (2 levels) in <top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => immigrant:check_keys
(See full trace by running task with --trace)
```

**Comment by prem-prakash** [comment]
Sorry it is working, I had a bad syntax in my code
